# Generated by Django 2.2.5 on 2019-09-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='First Name : '),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Last Name : '),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='mobilephone',
            field=models.CharField(max_length=100, verbose_name='Phone Number : '),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='resumetitle',
            field=models.CharField(max_length=200, verbose_name='Resume Title : '),
        ),
    ]
