# Generated by Django 2.2.5 on 2019-09-19 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190919_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Address '),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='city',
            field=models.CharField(blank=True, max_length=10, verbose_name='City '),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date '),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='First Name '),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Last Name '),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='mobilephone',
            field=models.CharField(max_length=100, verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='resumetitle',
            field=models.CharField(max_length=200, verbose_name='Resume Title '),
        ),
    ]
