# Generated by Django 2.2.5 on 2019-09-19 09:27

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190919_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='mobilephone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
