# Generated by Django 2.2.5 on 2019-09-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
