# Generated by Django 2.2.5 on 2019-09-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_personal_info_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='email',
        ),
    ]
