# Generated by Django 2.2.5 on 2019-09-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_personal_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
