# Generated by Django 2.2.5 on 2019-09-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_personal_info_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
    ]
