# Generated by Django 2.2.5 on 2019-09-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190919_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50, verbose_name='Skills ')),
                ('languages', models.CharField(max_length=50, verbose_name='Languages ')),
            ],
        ),
    ]
