# Generated by Django 2.2.5 on 2019-09-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='languages',
            field=models.CharField(blank=True, max_length=50, verbose_name='Languages '),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='skills',
            field=models.CharField(blank=True, max_length=50, verbose_name='Skills '),
        ),
    ]
