# Generated by Django 2.2.5 on 2019-09-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190919_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='skills',
            field=models.CharField(blank=True, max_length=500, verbose_name='Skills '),
        ),
    ]
