# Generated by Django 2.2.5 on 2019-09-21 16:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190921_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Html/Css', 'Html/Css'), ('Git', 'Git'), ('Javascripts', 'Javascripts'), ('Java', 'Javas'), ('C', 'C'), ('Php', 'Php'), ('Laravel', 'Laravel')], max_length=57),
        ),
    ]
