# Generated by Django 2.2.5 on 2019-09-21 17:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190921_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='degrees',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Bachelor', 'Bachelor'), ('MA', 'MA'), ('Doctorate', 'Doctorate')], max_length=21),
        ),
    ]
