# Generated by Django 2.2.5 on 2019-09-21 17:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190921_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='degrees',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bachelor', 'Bachelor'), ('MA', 'MA'), ('Doctorate', 'Doctorate')], default='Bachelor', max_length=21),
        ),
    ]
