# Generated by Django 2.2.5 on 2019-09-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190921_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='lastname',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
    ]
